default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: develop
  password: develop
development:
  <<: *default
  database: demo_tailwind_development
test:
  <<: *default
  database: demo_tailwind_test
production:
  <<: *default
  database: demo_tailwind_production
